server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.miracle.AMAG: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k8d102.p.ssafy.io:3306/SHARE42_TOGETHER?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ssafy
    password: ssafy123!@#

  data:
    redis:
      port: 6379
      host: k8d102.p.ssafy.io
      password: ssafy123!@#

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: debug

  mvc:
    view:
      prefix: /templates/
      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: validate #create update none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: com.miracle.AMAG.config.CamelCaseToSnakeAndUpperCaseStrategy

    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

image:
  url:
    windows: C:/Users/SSAFY/Downloads/images
    linux: /home/ubuntu/images

servlet:
  multipart:
    max-file-size: 20MB

klaytn:
  accessKeyId: KASK93KADR4ZKEZ04LN6PZQ8
  secretAccessKey: jKCjnMtIRt6TmnZSZkxpyJwTMqcelWoq8ZSP4u21
  authorization: Basic S0FTSzkzS0FEUjRaS0VaMDRMTjZQWlE4OmpLQ2puTXRJUnQ2VG1uWlNaa3hweUp3VE1xY2VsV29xOFpTUDR1MjE=
  chainId: 1001

kakao:
  restApiKey: 0fac24e59c08f0d24e738ea0377dc42a

naver:
  naver-cloud-sms:
    accessKey: xF55CRsMXSI3cRFneFPx
    secretKey: XJzENl8AETtcxiufSDv7wwtWtHoOWsVa3wGL0uQk
    serviceId: ncp:sms:kr:260663064935:share42
    senderPhone: 01092887883

bootPay:
  applicationID: 6449e6343049c8001c9e0720
  privateKey: oTLPbzaYINZa9dXzS9C1gjwKLXclvtke16O5XC0gsdQ=